require: rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2
  Exclude:
    - 'bin/**/*'     
    - 'db/**/*.rb'     
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/**/*'


Style/Documentation:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Metrics/MethodLength:
  Enabled: false